version: '2'
services:
  wordpress:
    image: wordpress:4.7.3
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=thoughtworks
      - WORDPRESS_DB_HOST=${DB_HOST}
    volumes:
      - ./themes/roundabout:/var/www/html/wp-content/themes/roundabout
      - ./themes/spike:/var/www/html/wp-content/themes/spike
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=thoughtworks
