version: '2'
services:
  wordpress:
    image: wordpress:4.7.3
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_NAME=round_about
      - WORDPRESS_DB_USER=${db_user}
      - WORDPRESS_DB_PASSWORD=${db_password}
      - WORDPRESS_DB_HOST=${db_host}
    volumes:
      - ./themes/roundabout:/var/www/html/wp-content/themes/roundabout
      - ./themes/spike:/var/www/html/wp-content/themes/spike
      - ./uploads:/var/www/html/wp-content/uploads
